version: '3'
services:

  app-db:
    container_name: app-db
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: interview_nhinguyen
    volumes:
      - ./crypto-service/src/main/resources/sql:/docker-entrypoint-initdb.d