server:
  port: 8080

spring:
  application:
    name: crypto-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/interview_nhinguyen?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      base-path: /${spring.application.name}

data-gateway:
  base-url: localhost:8081
